### PR TITLE
Fix: vterm new tab

### PR DESCRIPTION
**Pull request by black7375**
image
image

### CODE REVIEW

**Comment by lucasgruss** [comment]
ielm-vterm
This is odd, on my machine this does not work (see caption). 
What version of vterm are you using ? I am using vterm shipped with doom emacs, so I might have some configuration that gets in the way. I am investigating this.

**Comment by black7375** [comment]
The house is on the way, so I will check it after arrival
Probably the latest version.

**Comment by black7375** [comment]
current master version is correct

**Comment by lucasgruss** [comment]
So, Doom Emacs is actually pinned to a version of vterm that has a different entry point. My version is therefore older than yours. I will have to check with the Doom Emacs maintainers whether the version can be bumped to a more recent one, but I doubt it since the change on the vterm side will have to be adressed in a number of places on the doom side. 

Your fix is the right one, I am therefore merging it ! (Doom users are using a pinned version of centaur tabs and will not run into this issue until the version of centaur emacs is bumped, hopefully they will bump their version of vterm as well)

**Pull request merged**
